INSERT INTO ITEM(ID,NAME,PRICE, QUANTITY)
VALUES (1,'Computer', 5900, 10);

INSERT INTO ITEM(ID,NAME,PRICE, QUANTITY)
VALUES (2,'Notebook', 3500, 10);

INSERT INTO ITEM(ID,NAME,PRICE, QUANTITY)
VALUES (3,'Cell Phone', 1500, 10);

INSERT INTO ITEM(ID,NAME,PRICE, QUANTITY)
VALUES (4,'Camera', 2500, 10);

INSERT INTO USUARIO(CODIGO,ADMIN,CHAVE_GMAIL,EMAIL,NOME,SENHA)
VALUES(2,TRUE,NULL,'sentinela@gmail.com','ADMINISTRADOR_TEST', '$2a$10$Lq9W04f5W/7S8op/kWohrez7lPWXK3ELQAnePeM3Qe6vQt8G18tjS')